# Generated by Django 5.1.9 on 2025-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "ordering": ["name"],
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_mileage",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                help_text="Current odometer reading",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(
                blank=True, help_text="Unique license plate number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="purchase_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                blank=True,
                help_text="Vehicle Identification Number (optional)",
                max_length=17,
                null=True,
                unique=True,
            ),
        ),
    ]
