# Generated by Django 5.1.9 on 2025-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="memberalias",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
