# Generated by Django 5.1.9 on 2025-05-31 18:31

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_member_email_alter_memberalias_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="name",
            field=models.CharField(
                default=members.models.generate_unique_code, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
