# Generated by Django 5.1.9 on 2025-05-31 18:32

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("members", "Member")
    for row in MyModel.objects.all():
        row.name = str(uuid.uuid4())[:8]
        row.save(update_fields=["name"])

class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_name_alter_member_email"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
