# Generated by Django 5.1.9 on 2025-05-31 18:32
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_populate_member_name_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(
                default=members.models.generate_unique_code, max_length=50, unique=True
            ),
        ),
    ]
