# Generated by Django 5.1.9 on 2025-06-14 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_remove_member_name_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "Member", "verbose_name_plural": "Members"},
        ),
        migrations.AlterModelOptions(
            name="memberalias",
            options={
                "verbose_name": "Member alias",
                "verbose_name_plural": "Member aliases",
            },
        ),
        migrations.AlterField(
            model_name="memberalias",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Aliases",
                related_query_name="Alias",
                to="members.member",
            ),
        ),
    ]
