# Generated by Django 5.1.9 on 2025-06-14 21:41

import django.db.models.deletion
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_member_options_alter_memberalias_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["name"],
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
            },
        ),
        migrations.AlterModelOptions(
            name="memberalias",
            options={
                "ordering": ["name"],
                "verbose_name": "Member alias",
                "verbose_name_plural": "Member aliases",
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                help_text="Email address of the member (not necessarily unique)",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(
                default=members.models.generate_unique_code,
                help_text="Unique name or identifier for the member",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="memberalias",
            name="member",
            field=models.ForeignKey(
                help_text="The member this alias belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                related_query_name="alias",
                to="members.member",
            ),
        ),
        migrations.AlterField(
            model_name="memberalias",
            name="name",
            field=models.CharField(
                help_text="An alternative name or alias for the member",
                max_length=100,
                unique=True,
            ),
        ),
    ]
