# Generated by Django 5.1.9 on 2025-05-31 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_remove_member_name_null"),
        ("mileage_logs", "0002_mileagelog_file_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MileageLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ride_date", models.DateField()),
                (
                    "start",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ]
                    ),
                ),
                (
                    "end",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ]
                    ),
                ),
                ("is_long_distance", models.BooleanField(default=False)),
                ("destination", models.CharField(blank=True, max_length=100)),
                ("purpose", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("member", models.ManyToManyField(to="members.member")),
                (
                    "mileage_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mileage_logs.mileagelog",
                    ),
                ),
            ],
        ),
    ]
