# Generated by Django 5.1.9 on 2025-06-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mileage_logs", "0003_mileagelogentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mileagelogentry",
            name="mileage_log",
        ),
        migrations.RemoveField(
            model_name="mileagelogentry",
            name="member",
        ),
        migrations.DeleteModel(
            name="MileageLog",
        ),
        migrations.DeleteModel(
            name="MileageLogEntry",
        ),
    ]
