# Generated by Django 5.1.9 on 2025-07-24 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mileage_logs", "0006_alter_mileagelogentry_distance_traveled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mileageclaim",
            name="number_of_seats_claimed",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of seats claimed by this member for this trip.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
